@startuml

entity ApplicationRole {
    Id : Guid
    --
    ApplicationUserRoles : ICollection<ApplicationUserRole>
    ApplicationUserUpdatedBy : ApplicationUser
    --
    ConcurrencyStamp : string
    Name : string
    NormalizedName : string
}

entity ApplicationRoleClaim {
    Id : int
    --
    ApplicationUserUpdatedBy : ApplicationUser
    RoleId : Guid
    --
    ClaimType : string
    ClaimValue : string
}

entity ApplicationUser {
    Id : Guid
    --
    ApplicationUserRoles : ICollection<ApplicationUserRole>
    ApplicationUserUpdatedBy : ApplicationUser
    UpdatedApplicationRoles : ICollection<ApplicationRole>
    UpdatedApplicationRoleClaims : ICollection<ApplicationRoleClaim>
    UpdatedApplicationUsers : ICollection<ApplicationUser>
    UpdatedApplicationUserClaims : ICollection<ApplicationUserClaim>
    UpdatedApplicationUserLogins : ICollection<ApplicationUserLogin>
    UpdatedApplicationUserRoles : ICollection<ApplicationUserRole>
    UpdatedApplicationUserTokens : ICollection<ApplicationUserToken>
    UpdatedCards : ICollection<Card>
    UpdatedCardFoundations : ICollection<CardFoundation>
    UpdatedCardStocks : ICollection<CardStock>
    UpdatedCardTableaus : ICollection<CardTableau>
    UpdatedCardWastes : ICollection<CardWaste>
    UpdatedFoundations : ICollection<Foundation>
    UpdatedGames : ICollection<Game>
    ' ApplicationUserKeyCodePlaceholder
    --
    AccessFailedCount : int
    ConcurrencyStamp : string
    Email : string
    EmailConfirmed : bool
    LockoutEnabled : bool
    LockoutEnd : DateTimeOffset
    NormalizedEmail : string
    NormalizedUserName : string
    PasswordHash : string
    PhoneNumber : string
    PhoneNumberConfirmed : bool
    SecurityStamp : string
    TwoFactorEnabled: bool
    UserName : string
}

entity ApplicationUserClaim {
    Id : int
    --
    ApplicationUserUpdatedBy : ApplicationUser
    UserId : Guid
    --
    ClaimType : string
    ClaimValue : string
}

entity ApplicationUserLogin {
    --
    ApplicationUserUpdatedBy : ApplicationUser
    UserId : Guid
    --
    LoginProvider
    ProviderDisplayName
    ProviderKey
}

entity ApplicationUserRole {
    --
    ApplicationRole : ApplicationRole
    ApplicationUser : ApplicationUser
    ApplicationUserUpdatedBy : ApplicationUser
    RoleId : Guid
    UserId : Guid
    --
}

entity ApplicationUserToken {
    --
    ApplicationUserUpdatedBy : ApplicationUser
    UserId : Guid
    --
    LoginProvider : string
    Name : string
    Value : string
}

entity Card {
    Id : Guid
    --
    ApplicationUserUpdatedBy : ApplicationUser
    RankId : Rank
    SuitId : Suit
    CardFoundations : ICollection<CardFoundation>
    CardStocks : ICollection<CardStock>
    CardTableaus : ICollection<CardTableau>
    CardWastes : ICollection<CardWaste>
    MovesAsCard1 : ICollection<Move>
    MovesAsCard2 : ICollection<Move>
    MovesAsCard3 : ICollection<Move>
    ' CardKeyCodePlaceholder
    --
    ' CardPropertyCodePlaceholder
}

entity CardFoundation {
    Id : Guid
    --
    ApplicationUserUpdatedBy : ApplicationUser
    Card : Card
    Foundation : Foundation
    ' CardFoundationKeyCodePlaceholder
    --
    Ordering : int
    ' CardFoundationPropertyCodePlaceholder
}

entity CardStock {
    Id : Guid
    --
    ApplicationUserUpdatedBy : ApplicationUser
    CardId : Card
    GameId : Game
    PuzzleId : Puzzle
    ' CardStockKeyCodePlaceholder
    --
    Ordering : int
    ' CardStockPropertyCodePlaceholder
}

entity CardTableau {
    Id : Guid
    --
    ApplicationUserUpdatedBy : ApplicationUser
    CardId : Card
    TableauId : Tableau
    ' CardTableauKeyCodePlaceholder
    --
    Ordering : int
    ' CardTableauPropertyCodePlaceholder
}

entity CardWaste {
    Id : Guid
    --
    ApplicationUserUpdatedBy : ApplicationUser
    CardId : Card
    GameId : Game
    PuzzleId : Puzzle
    ' CardWasteKeyCodePlaceholder
    --
    Ordering : int
    ' CardWastePropertyCodePlaceholder
}

entity Foundation {
    Id : Guid
    --
    ApplicationUserUpdatedBy : ApplicationUser
    GameId : Game
    PuzzleId : Puzzle
    SuitId : Suit
    CardFoundations : ICollection<CardFoundation>
    ' FoundationKeyCodePlaceholder
    --
    PileIndex : int
    ' FoundationPropertyCodePlaceholder
}

entity Game {
    Id : Guid
    --
    ApplicationUserUpdatedBy : ApplicationUser
    PlayerId : Player
    ' GameKeyCodePlaceholder
    --
    EndTime : DateTime
    ' GamePropertyCodePlaceholder
}

' EntityCodePlaceholder

ApplicationRole ||--o{ ApplicationUserRole
ApplicationRole }o--|| ApplicationUser
ApplicationRoleClaim }o--|| ApplicationRole
ApplicationRoleClaim }o--|| ApplicationUser
ApplicationUser }o--|| ApplicationUser
ApplicationUser ||--o{ ApplicationUserRole
ApplicationUserClaim }o--|| ApplicationUser
ApplicationUserLogin }o--|| ApplicationUser
ApplicationUserRole }o--|| ApplicationUser
ApplicationUserToken }o--|| ApplicationUser

Card }o--|| ApplicationUser
Card }o--|| Rank
Card }o--|| Suit
CardFoundation }o--|| ApplicationUser
CardFoundation }o--|| Card
CardFoundation }o--|| Foundation
CardStock }o--|| ApplicationUser
CardStock }o--|| Card
CardStock }o--|| Game
CardStock }o--|| Puzzle
CardTableau }o--|| ApplicationUser
CardTableau }o--|| Card
CardTableau }o--|| Tableau
CardWaste }o--|| ApplicationUser
CardWaste }o--|| Card
CardWaste }o--|| Game
CardWaste }o--|| Puzzle
Foundation }o--|| ApplicationUser
Foundation }o--|| Game
Foundation }o--|| Puzzle
Foundation }o--|| Suit
Game }o--|| ApplicationUser
' RelationshipCodePlaceholder

@enduml
